### ISSUE TITLE
Hi Simon

### ISSUE THREAD

**Issue by tapanagkumar** [Simon-Kaz/AppiumFindByImage#1]
Thank you very much for providing the OCR.java file. I am using the file to recognize the images. 
I am getting an error when I am using 

Explicit wait for Images method.

 /*\* 
      \* Custom explicit wait method that waits for @timeoutDuration until element is visible. 
        */ 
    public void waitUntilImageExists(final String targetImgPath, long timeoutDuration) { 
    new WebDriverWait(driver, timeoutDuration).until((WebDriver driver) -> elementExists(targetImgPath)); 

Please Help

![issue](https://cloud.githubusercontent.com/assets/15642428/13323558/07ad4bb4-dc00-11e5-9c86-d74133e1f48e.png)

**Comment by Simon-Kaz** [comment]
Hi, apologies for the delay in response. Are you on java 8 and have you specified it at the Project language level?

**Comment by tapanagkumar** [comment]
Hi Simon,
I am on java 7, not on Java 8. I am trying to upgrade my compiler to 1.8

Regards
Gowri Kumar

**Comment by tapanagkumar** [comment]
Hi Simon,
When i set my environment to Java 8, i dont see the error message. My Bad, the issue is with my setup. Thanks for letting me know.

**Comment by Simon-Kaz** [comment]
No problem! Enjoy.

**Comment by messianic** [comment]
Hi Simon
The same issue even though I'm using Java 8. Please Help!

**Comment by ishansaini** [comment]
@Simon-Kaz  The issue persists  even though I'm using Java 8. Please Help!

**Comment by Simon-Kaz** [comment]
hi @messianic , could you post appium logs and the stacktrace? Thanks!
