### ISSUE TITLE
Text Recognition and Long Press

### ISSUE THREAD

**Issue by goncalosoares** [Simon-Kaz/AppiumFindByImage#2]
Hey,

I looked at this project and looks awesome!
Wouldn't also be the possibility of long press (maybe by adding and argument to the clickByImage method). This i believe I could change myself :-)
Also it could be very cool if it would have text recognition... like that you could find a text string instead of a picture... What do you think?

Best,
Goncalo

**Comment by Simon-Kaz** [comment]
Hey @TheJusticeLeague , thanks for kind words and apologies for responding so late, Github failed to notify me :)

I updated the project with a new method, longPressByImage. Default duration is 1 second, but you can pass your own duration as well via the overloaded method.

As for the text recognition - it wouldn't work with the current Sikuli implementation (remote find by).
I'm checking sikuli-x periodically, as there are going to be changes to how remote image comparison is done.
